/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - dist/StandardizedTokenMintBurn.sol/StandardizedTokenMintBurn.sol/StandardizedTokenMintBurn.json
 *
 * DO NOT EDIT MANUALLY
 */

import { encodeFunctionData } from "viem";

import ABI_FILE from "./StandardizedTokenMintBurn.abi";

export type StandardizedTokenMintBurnApproveArgs = {
  spender: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenMintBurn.approve function args
 */
export const encodeStandardizedTokenMintBurnApproveArgs = ({
  spender,
  amount,
}: StandardizedTokenMintBurnApproveArgs) => [spender, amount] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.approve function data
 */
export const encodeStandardizedTokenMintBurnApproveData = ({
  spender,
  amount,
}: StandardizedTokenMintBurnApproveArgs) =>
  encodeFunctionData({
    functionName: "approve",
    abi: ABI_FILE.abi,
    args: [spender, amount],
  });

export type StandardizedTokenMintBurnBurnArgs = {
  account: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenMintBurn.burn function args
 */
export const encodeStandardizedTokenMintBurnBurnArgs = ({
  account,
  amount,
}: StandardizedTokenMintBurnBurnArgs) => [account, amount] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.burn function data
 */
export const encodeStandardizedTokenMintBurnBurnData = ({
  account,
  amount,
}: StandardizedTokenMintBurnBurnArgs) =>
  encodeFunctionData({
    functionName: "burn",
    abi: ABI_FILE.abi,
    args: [account, amount],
  });

export type StandardizedTokenMintBurnDecreaseAllowanceArgs = {
  spender: `0x${string}`;
  subtractedValue: bigint;
};

/**
 * Factory function for StandardizedTokenMintBurn.decreaseAllowance function args
 */
export const encodeStandardizedTokenMintBurnDecreaseAllowanceArgs = ({
  spender,
  subtractedValue,
}: StandardizedTokenMintBurnDecreaseAllowanceArgs) =>
  [spender, subtractedValue] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.decreaseAllowance function data
 */
export const encodeStandardizedTokenMintBurnDecreaseAllowanceData = ({
  spender,
  subtractedValue,
}: StandardizedTokenMintBurnDecreaseAllowanceArgs) =>
  encodeFunctionData({
    functionName: "decreaseAllowance",
    abi: ABI_FILE.abi,
    args: [spender, subtractedValue],
  });

export type StandardizedTokenMintBurnIncreaseAllowanceArgs = {
  spender: `0x${string}`;
  addedValue: bigint;
};

/**
 * Factory function for StandardizedTokenMintBurn.increaseAllowance function args
 */
export const encodeStandardizedTokenMintBurnIncreaseAllowanceArgs = ({
  spender,
  addedValue,
}: StandardizedTokenMintBurnIncreaseAllowanceArgs) =>
  [spender, addedValue] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.increaseAllowance function data
 */
export const encodeStandardizedTokenMintBurnIncreaseAllowanceData = ({
  spender,
  addedValue,
}: StandardizedTokenMintBurnIncreaseAllowanceArgs) =>
  encodeFunctionData({
    functionName: "increaseAllowance",
    abi: ABI_FILE.abi,
    args: [spender, addedValue],
  });

export type StandardizedTokenMintBurnInterchainTransferArgs = {
  destinationChain: string;
  recipient: `0x${string}`;
  amount: bigint;
  metadata: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenMintBurn.interchainTransfer function args
 */
export const encodeStandardizedTokenMintBurnInterchainTransferArgs = ({
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenMintBurnInterchainTransferArgs) =>
  [destinationChain, recipient, amount, metadata] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.interchainTransfer function data
 */
export const encodeStandardizedTokenMintBurnInterchainTransferData = ({
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenMintBurnInterchainTransferArgs) =>
  encodeFunctionData({
    functionName: "interchainTransfer",
    abi: ABI_FILE.abi,
    args: [destinationChain, recipient, amount, metadata],
  });

export type StandardizedTokenMintBurnInterchainTransferFromArgs = {
  sender: `0x${string}`;
  destinationChain: string;
  recipient: `0x${string}`;
  amount: bigint;
  metadata: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenMintBurn.interchainTransferFrom function args
 */
export const encodeStandardizedTokenMintBurnInterchainTransferFromArgs = ({
  sender,
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenMintBurnInterchainTransferFromArgs) =>
  [sender, destinationChain, recipient, amount, metadata] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.interchainTransferFrom function data
 */
export const encodeStandardizedTokenMintBurnInterchainTransferFromData = ({
  sender,
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenMintBurnInterchainTransferFromArgs) =>
  encodeFunctionData({
    functionName: "interchainTransferFrom",
    abi: ABI_FILE.abi,
    args: [sender, destinationChain, recipient, amount, metadata],
  });

export type StandardizedTokenMintBurnMintArgs = {
  account: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenMintBurn.mint function args
 */
export const encodeStandardizedTokenMintBurnMintArgs = ({
  account,
  amount,
}: StandardizedTokenMintBurnMintArgs) => [account, amount] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.mint function data
 */
export const encodeStandardizedTokenMintBurnMintData = ({
  account,
  amount,
}: StandardizedTokenMintBurnMintArgs) =>
  encodeFunctionData({
    functionName: "mint",
    abi: ABI_FILE.abi,
    args: [account, amount],
  });

export type StandardizedTokenMintBurnPermitArgs = {
  issuer: `0x${string}`;
  spender: `0x${string}`;
  value: bigint;
  deadline: bigint;
  v: number;
  r: `0x${string}`;
  s: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenMintBurn.permit function args
 */
export const encodeStandardizedTokenMintBurnPermitArgs = ({
  issuer,
  spender,
  value,
  deadline,
  v,
  r,
  s,
}: StandardizedTokenMintBurnPermitArgs) =>
  [issuer, spender, value, deadline, v, r, s] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.permit function data
 */
export const encodeStandardizedTokenMintBurnPermitData = ({
  issuer,
  spender,
  value,
  deadline,
  v,
  r,
  s,
}: StandardizedTokenMintBurnPermitArgs) =>
  encodeFunctionData({
    functionName: "permit",
    abi: ABI_FILE.abi,
    args: [issuer, spender, value, deadline, v, r, s],
  });

export type StandardizedTokenMintBurnSetDistributorArgs = {
  distr: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenMintBurn.setDistributor function args
 */
export const encodeStandardizedTokenMintBurnSetDistributorArgs = ({
  distr,
}: StandardizedTokenMintBurnSetDistributorArgs) => [distr] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.setDistributor function data
 */
export const encodeStandardizedTokenMintBurnSetDistributorData = ({
  distr,
}: StandardizedTokenMintBurnSetDistributorArgs) =>
  encodeFunctionData({
    functionName: "setDistributor",
    abi: ABI_FILE.abi,
    args: [distr],
  });

export type StandardizedTokenMintBurnSetupArgs = { params: `0x${string}` };

/**
 * Factory function for StandardizedTokenMintBurn.setup function args
 */
export const encodeStandardizedTokenMintBurnSetupArgs = ({
  params,
}: StandardizedTokenMintBurnSetupArgs) => [params] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.setup function data
 */
export const encodeStandardizedTokenMintBurnSetupData = ({
  params,
}: StandardizedTokenMintBurnSetupArgs) =>
  encodeFunctionData({
    functionName: "setup",
    abi: ABI_FILE.abi,
    args: [params],
  });

export type StandardizedTokenMintBurnTransferArgs = {
  recipient: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenMintBurn.transfer function args
 */
export const encodeStandardizedTokenMintBurnTransferArgs = ({
  recipient,
  amount,
}: StandardizedTokenMintBurnTransferArgs) => [recipient, amount] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.transfer function data
 */
export const encodeStandardizedTokenMintBurnTransferData = ({
  recipient,
  amount,
}: StandardizedTokenMintBurnTransferArgs) =>
  encodeFunctionData({
    functionName: "transfer",
    abi: ABI_FILE.abi,
    args: [recipient, amount],
  });

export type StandardizedTokenMintBurnTransferFromArgs = {
  sender: `0x${string}`;
  recipient: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenMintBurn.transferFrom function args
 */
export const encodeStandardizedTokenMintBurnTransferFromArgs = ({
  sender,
  recipient,
  amount,
}: StandardizedTokenMintBurnTransferFromArgs) =>
  [sender, recipient, amount] as const;

/**
 * Encoder function for StandardizedTokenMintBurn.transferFrom function data
 */
export const encodeStandardizedTokenMintBurnTransferFromData = ({
  sender,
  recipient,
  amount,
}: StandardizedTokenMintBurnTransferFromArgs) =>
  encodeFunctionData({
    functionName: "transferFrom",
    abi: ABI_FILE.abi,
    args: [sender, recipient, amount],
  });
