/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - dist/TokenManagerMintBurn.sol/TokenManagerMintBurn.sol/TokenManagerMintBurn.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../client/PublicContractClient";
import ABI_FILE from "./TokenManagerMintBurn.abi";

export * from "./TokenManagerMintBurn.args";

export const TOKENMANAGERMINTBURN_ABI = ABI_FILE.abi;

export class TokenManagerMintBurnClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: TOKENMANAGERMINTBURN_ABI,
      address: options.address,
      chain: options.chain,
    });
  }
}
