/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - dist/ERC20.sol/ERC20.sol/ERC20.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../client/PublicContractClient";
import ABI_FILE from "./ERC20.abi";

export * from "./ERC20.args";

export const ERC20_ABI = ABI_FILE.abi;

export class ERC20Client extends PublicContractClient<typeof ABI_FILE.abi> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: ERC20_ABI,
      address: options.address,
      chain: options.chain,
    });
  }
}
