/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - dist/TokenManagerLiquidityPool.sol/TokenManagerLiquidityPool.sol/TokenManagerLiquidityPool.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../client/PublicContractClient";
import ABI_FILE from "./TokenManagerLiquidityPool.abi";

export * from "./TokenManagerLiquidityPool.args";

export const TOKENMANAGERLIQUIDITYPOOL_ABI = ABI_FILE.abi;

export class TokenManagerLiquidityPoolClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: TOKENMANAGERLIQUIDITYPOOL_ABI,
      address: options.address,
      chain: options.chain,
    });
  }
}
