/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - dist/StandardizedTokenLockUnlock.sol/StandardizedTokenLockUnlock.sol/StandardizedTokenLockUnlock.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../client/PublicContractClient";
import ABI_FILE from "./StandardizedTokenLockUnlock.abi";

export * from "./StandardizedTokenLockUnlock.args";

export const STANDARDIZEDTOKENLOCKUNLOCK_ABI = ABI_FILE.abi;

export class StandardizedTokenLockUnlockClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: STANDARDIZEDTOKENLOCKUNLOCK_ABI,
      address: options.address,
      chain: options.chain,
    });
  }
}
