/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - dist/StandardizedTokenLockUnlock.sol/StandardizedTokenLockUnlock.sol/StandardizedTokenLockUnlock.json
 *
 * DO NOT EDIT MANUALLY
 */

import { encodeFunctionData } from "viem";

import ABI_FILE from "./StandardizedTokenLockUnlock.abi";

export type StandardizedTokenLockUnlockApproveArgs = {
  spender: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenLockUnlock.approve function args
 */
export const encodeStandardizedTokenLockUnlockApproveArgs = ({
  spender,
  amount,
}: StandardizedTokenLockUnlockApproveArgs) => [spender, amount] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.approve function data
 */
export const encodeStandardizedTokenLockUnlockApproveData = ({
  spender,
  amount,
}: StandardizedTokenLockUnlockApproveArgs) =>
  encodeFunctionData({
    functionName: "approve",
    abi: ABI_FILE.abi,
    args: [spender, amount],
  });

export type StandardizedTokenLockUnlockBurnArgs = {
  account: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenLockUnlock.burn function args
 */
export const encodeStandardizedTokenLockUnlockBurnArgs = ({
  account,
  amount,
}: StandardizedTokenLockUnlockBurnArgs) => [account, amount] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.burn function data
 */
export const encodeStandardizedTokenLockUnlockBurnData = ({
  account,
  amount,
}: StandardizedTokenLockUnlockBurnArgs) =>
  encodeFunctionData({
    functionName: "burn",
    abi: ABI_FILE.abi,
    args: [account, amount],
  });

export type StandardizedTokenLockUnlockDecreaseAllowanceArgs = {
  spender: `0x${string}`;
  subtractedValue: bigint;
};

/**
 * Factory function for StandardizedTokenLockUnlock.decreaseAllowance function args
 */
export const encodeStandardizedTokenLockUnlockDecreaseAllowanceArgs = ({
  spender,
  subtractedValue,
}: StandardizedTokenLockUnlockDecreaseAllowanceArgs) =>
  [spender, subtractedValue] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.decreaseAllowance function data
 */
export const encodeStandardizedTokenLockUnlockDecreaseAllowanceData = ({
  spender,
  subtractedValue,
}: StandardizedTokenLockUnlockDecreaseAllowanceArgs) =>
  encodeFunctionData({
    functionName: "decreaseAllowance",
    abi: ABI_FILE.abi,
    args: [spender, subtractedValue],
  });

export type StandardizedTokenLockUnlockIncreaseAllowanceArgs = {
  spender: `0x${string}`;
  addedValue: bigint;
};

/**
 * Factory function for StandardizedTokenLockUnlock.increaseAllowance function args
 */
export const encodeStandardizedTokenLockUnlockIncreaseAllowanceArgs = ({
  spender,
  addedValue,
}: StandardizedTokenLockUnlockIncreaseAllowanceArgs) =>
  [spender, addedValue] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.increaseAllowance function data
 */
export const encodeStandardizedTokenLockUnlockIncreaseAllowanceData = ({
  spender,
  addedValue,
}: StandardizedTokenLockUnlockIncreaseAllowanceArgs) =>
  encodeFunctionData({
    functionName: "increaseAllowance",
    abi: ABI_FILE.abi,
    args: [spender, addedValue],
  });

export type StandardizedTokenLockUnlockInterchainTransferArgs = {
  destinationChain: string;
  recipient: `0x${string}`;
  amount: bigint;
  metadata: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenLockUnlock.interchainTransfer function args
 */
export const encodeStandardizedTokenLockUnlockInterchainTransferArgs = ({
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenLockUnlockInterchainTransferArgs) =>
  [destinationChain, recipient, amount, metadata] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.interchainTransfer function data
 */
export const encodeStandardizedTokenLockUnlockInterchainTransferData = ({
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenLockUnlockInterchainTransferArgs) =>
  encodeFunctionData({
    functionName: "interchainTransfer",
    abi: ABI_FILE.abi,
    args: [destinationChain, recipient, amount, metadata],
  });

export type StandardizedTokenLockUnlockInterchainTransferFromArgs = {
  sender: `0x${string}`;
  destinationChain: string;
  recipient: `0x${string}`;
  amount: bigint;
  metadata: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenLockUnlock.interchainTransferFrom function args
 */
export const encodeStandardizedTokenLockUnlockInterchainTransferFromArgs = ({
  sender,
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenLockUnlockInterchainTransferFromArgs) =>
  [sender, destinationChain, recipient, amount, metadata] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.interchainTransferFrom function data
 */
export const encodeStandardizedTokenLockUnlockInterchainTransferFromData = ({
  sender,
  destinationChain,
  recipient,
  amount,
  metadata,
}: StandardizedTokenLockUnlockInterchainTransferFromArgs) =>
  encodeFunctionData({
    functionName: "interchainTransferFrom",
    abi: ABI_FILE.abi,
    args: [sender, destinationChain, recipient, amount, metadata],
  });

export type StandardizedTokenLockUnlockMintArgs = {
  account: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenLockUnlock.mint function args
 */
export const encodeStandardizedTokenLockUnlockMintArgs = ({
  account,
  amount,
}: StandardizedTokenLockUnlockMintArgs) => [account, amount] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.mint function data
 */
export const encodeStandardizedTokenLockUnlockMintData = ({
  account,
  amount,
}: StandardizedTokenLockUnlockMintArgs) =>
  encodeFunctionData({
    functionName: "mint",
    abi: ABI_FILE.abi,
    args: [account, amount],
  });

export type StandardizedTokenLockUnlockPermitArgs = {
  issuer: `0x${string}`;
  spender: `0x${string}`;
  value: bigint;
  deadline: bigint;
  v: number;
  r: `0x${string}`;
  s: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenLockUnlock.permit function args
 */
export const encodeStandardizedTokenLockUnlockPermitArgs = ({
  issuer,
  spender,
  value,
  deadline,
  v,
  r,
  s,
}: StandardizedTokenLockUnlockPermitArgs) =>
  [issuer, spender, value, deadline, v, r, s] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.permit function data
 */
export const encodeStandardizedTokenLockUnlockPermitData = ({
  issuer,
  spender,
  value,
  deadline,
  v,
  r,
  s,
}: StandardizedTokenLockUnlockPermitArgs) =>
  encodeFunctionData({
    functionName: "permit",
    abi: ABI_FILE.abi,
    args: [issuer, spender, value, deadline, v, r, s],
  });

export type StandardizedTokenLockUnlockSetDistributorArgs = {
  distr: `0x${string}`;
};

/**
 * Factory function for StandardizedTokenLockUnlock.setDistributor function args
 */
export const encodeStandardizedTokenLockUnlockSetDistributorArgs = ({
  distr,
}: StandardizedTokenLockUnlockSetDistributorArgs) => [distr] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.setDistributor function data
 */
export const encodeStandardizedTokenLockUnlockSetDistributorData = ({
  distr,
}: StandardizedTokenLockUnlockSetDistributorArgs) =>
  encodeFunctionData({
    functionName: "setDistributor",
    abi: ABI_FILE.abi,
    args: [distr],
  });

export type StandardizedTokenLockUnlockSetupArgs = { params: `0x${string}` };

/**
 * Factory function for StandardizedTokenLockUnlock.setup function args
 */
export const encodeStandardizedTokenLockUnlockSetupArgs = ({
  params,
}: StandardizedTokenLockUnlockSetupArgs) => [params] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.setup function data
 */
export const encodeStandardizedTokenLockUnlockSetupData = ({
  params,
}: StandardizedTokenLockUnlockSetupArgs) =>
  encodeFunctionData({
    functionName: "setup",
    abi: ABI_FILE.abi,
    args: [params],
  });

export type StandardizedTokenLockUnlockTransferArgs = {
  recipient: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenLockUnlock.transfer function args
 */
export const encodeStandardizedTokenLockUnlockTransferArgs = ({
  recipient,
  amount,
}: StandardizedTokenLockUnlockTransferArgs) => [recipient, amount] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.transfer function data
 */
export const encodeStandardizedTokenLockUnlockTransferData = ({
  recipient,
  amount,
}: StandardizedTokenLockUnlockTransferArgs) =>
  encodeFunctionData({
    functionName: "transfer",
    abi: ABI_FILE.abi,
    args: [recipient, amount],
  });

export type StandardizedTokenLockUnlockTransferFromArgs = {
  sender: `0x${string}`;
  recipient: `0x${string}`;
  amount: bigint;
};

/**
 * Factory function for StandardizedTokenLockUnlock.transferFrom function args
 */
export const encodeStandardizedTokenLockUnlockTransferFromArgs = ({
  sender,
  recipient,
  amount,
}: StandardizedTokenLockUnlockTransferFromArgs) =>
  [sender, recipient, amount] as const;

/**
 * Encoder function for StandardizedTokenLockUnlock.transferFrom function data
 */
export const encodeStandardizedTokenLockUnlockTransferFromData = ({
  sender,
  recipient,
  amount,
}: StandardizedTokenLockUnlockTransferFromArgs) =>
  encodeFunctionData({
    functionName: "transferFrom",
    abi: ABI_FILE.abi,
    args: [sender, recipient, amount],
  });
