/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * This file was generated by scripts/codegen.ts
 *
 * Original abi file:
 * - dist/ERC20Permit.sol/ERC20Permit.sol/ERC20Permit.json
 *
 * DO NOT EDIT MANUALLY
 */

import { Chain } from "viem";

import { PublicContractClient } from "../../client/PublicContractClient";
import ABI_FILE from "./ERC20Permit.abi";

export * from "./ERC20Permit.args";

export const ERC20PERMIT_ABI = ABI_FILE.abi;

export class ERC20PermitClient extends PublicContractClient<
  typeof ABI_FILE.abi
> {
  static ABI = ABI_FILE.abi;
  static contractName = ABI_FILE.contractName;

  constructor(options: { chain: Chain; address: `0x${string}` }) {
    super({
      abi: ERC20PERMIT_ABI,
      address: options.address,
      chain: options.chain,
    });
  }
}
